In [ ]:
import pandas as pd
import numpy as np
import sqlite3 as db
from datetime import datetime
import urllib
import os



con = db.connect(database="../db.sqlite")

In [ ]:

cursor = con.cursor()
cursor.execute("select CountryCode, Name from Country")

list = []

for row in cursor.fetchall():
    list.append({
        "CountryCode": row[0],
        "Country": row[1]
    })
    

def getCountryCode(name):
    
    if name == "United Kingdom":
        return "GBR"
    elif name == "Russian Federation":
        return "RUS"
    elif name == "Korea":
        return "KOR"
    elif name == "Slovak Republic":
        return "SVK"
    
    for c in list:
        if c["Country"] == name:
            return c["CountryCode"]
        
    return None

In [ ]:
xl = pd.ExcelFile("Average Tax Wedges 2020.xlsx")

df = xl.parse(0)

df["Source"] = "oecd"
df["Country"] = df["Country"].apply(lambda x: x.strip())

In [ ]:
## replace with country code

dfKeys = df.groupby("Country").groups.keys()


for key in dfKeys:
    if getCountryCode(key) == None:
        print(key + " does not exist in db")
        
        
df["Country"] = df["Country"].apply(lambda x: getCountryCode(x))

In [ ]:
dfFam2 = df[["Country", "Family 2 Total Tax Wedge", "Source"]]
dfFam2.rename(columns={"Family 2 Total Tax Wedge": "Rate", "Country": "Country_id"},inplace=True)
dfFam2["Rate"] = dfFam2["Rate"] / 100
dfFam2["Profession"] = "General Family of 2"
dfFam2["Date"] = datetime(2020,1,1)
dfFam2.to_sql("TaxWedge", con,if_exists="append", index=False)

In [ ]:
dfSingle = df[["Country", "Single Tax Wedge", "Source"]]
dfSingle.rename(columns={"Single Tax Wedge": "Rate", "Country": "Country_id"},inplace=True)
dfSingle["Rate"] = dfSingle["Rate"] / 100
dfSingle["Profession"] = "General"
dfSingle["Date"] = datetime(2020,1,1)
dfSingle.to_sql("TaxWedge", con,if_exists="append", index=False)

In [16]:
df["Family 2 Total Tax Wedge"] = df["Family 2 Total Tax Wedge"] - df["Family Annual Change"]
df["Single Tax Wedge"] = df["Single Tax Wedge"] - df["Single Annual Change"]

In [17]:
df

,Country,Family 2 Total Tax Wedge,Single Tax Wedge,Family Annual Change,Single Annual Change,Difference Between Family and Single,Source
0,TUR,38.04,39.61,0.16,0.09,-0.08,oecd
1,FRA,38.67,47.16,-0.77,-0.56,0.21,oecd
2,SWE,37.29,42.61,0.21,0.09,-0.12,oecd
3,GRC,37.92,40.90,-0.82,-0.80,0.02,oecd
4,FIN,37.70,42.12,-1.00,-0.92,0.07,oecd
5,ITA,39.08,47.91,-2.68,-1.91,0.77,oecd
6,BEL,36.61,52.26,-1.71,-0.76,0.95,oecd
7,ESP,34.06,39.42,-0.16,-0.12,0.04,oecd
8,DEU,34.28,49.28,-1.38,-0.28,1.10,oecd
9,NOR,32.16,35.76,0.04,0.04,0.01,oecd
10,AUT,33.66,47.86,-1.66,-0.56,1.10,oecd
11,LVA,32.23,42.42,-1.13,-0.62,0.51,oecd
12,HUN,30.32,44.54,-0.22,-0.94,-0.72,oecd
13,SVK,30.98,41.82,-0.88,-0.62,0.25,oecd
14,NLD,31.93,36.94,-1.93,-0.54,1.39,oecd
15,PRT,29.92,41.24,0.08,0.06,-0.02,oecd
16,JPN,27.56,32.72,-0.06,-0.02,0.04,oecd
17,EST,27.04,37.03,-0.24,-0.13,0.11,oecd
18,GBR,26.49,30.90,-0.09,-0.10,-0.02,oecd
19,CZE,26.47,43.93,-0.37,-0.03,0.34,oecd
20,SVN,25.74,43.45,-0.24,-0.55,-0.31,oecd
21,DNK,25.33,35.45,-0.23,-0.25,-0.02,oecd
22,AUS,20.73,27.98,0.07,0.42,0.34,oecd
23,MEX,20.21,20.21,-0.01,-0.01,0.00,oecd
24,LTU,29.98,37.66,-9.88,-0.76,9.12,oecd
25,ISR,20.50,22.93,-0.60,-0.53,0.07,oecd
26,ICE,19.87,32.74,-1.27,-0.44,0.82,oecd
27,KOR,20.36,22.99,-2.06,0.31,2.36,oecd
28,LUX,17.42,38.42,-1.12,-0.92,0.20,oecd
29,IRL,17.81,33.16,-1.71,-0.86,0.85,oecd
30,USA,18.62,29.67,-4.62,-1.37,3.25,oecd
31,POL,17.52,35.56,-4.32,-0.76,3.56,oecd
32,CAN,12.20,30.55,-2.10,-0.15,1.95,oecd
33,CHE,9.97,22.32,-0.37,-0.22,0.15,oecd
34,CHL,7.00,7.01,0.00,-0.01,-0.01,oecd
35,NZL,3.42,18.76,1.58,0.34,-1.24,oecd
36,COL,-4.38,0.00,-1.02,0.00,1.02,oecd

In [18]:
dfFam2 = df[["Country", "Family 2 Total Tax Wedge", "Source"]]
dfFam2.rename(columns={"Family 2 Total Tax Wedge": "Rate", "Country": "Country_id"},inplace=True)
dfFam2["Rate"] = dfFam2["Rate"] / 100
dfFam2["Profession"] = "General Family of 2"
dfFam2["Date"] = datetime(2019,1,1)
dfFam2.to_sql("TaxWedge", con,if_exists="append", index=False)

C:\Users\egonu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(
C:\Users\egonu\AppData\Local\Temp/ipykernel_12104/1120189950.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfFam2["Rate"] = dfFam2["Rate"] / 100
C:\Users\egonu\AppData\Local\Temp/ipykernel_12104/1120189950.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfFam2["Profession"] = "General Family of 2"
C:\Users\egonu\AppData\Local\Temp/ipykernel_12104/1120189950.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfFam2["Date"] = datetime(2019,1,1)

In [19]:
dfSingle = df[["Country", "Single Tax Wedge", "Source"]]
dfSingle.rename(columns={"Single Tax Wedge": "Rate", "Country": "Country_id"},inplace=True)
dfSingle["Rate"] = dfSingle["Rate"] / 100
dfSingle["Profession"] = "General"
dfSingle["Date"] = datetime(2019,1,1)
dfSingle.to_sql("TaxWedge", con,if_exists="append", index=False)

C:\Users\egonu\AppData\Local\Temp/ipykernel_12104/2405583668.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSingle["Rate"] = dfSingle["Rate"] / 100
C:\Users\egonu\AppData\Local\Temp/ipykernel_12104/2405583668.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSingle["Profession"] = "General"
C:\Users\egonu\AppData\Local\Temp/ipykernel_12104/2405583668.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSingle["Date"] = datetime(2019,1,1)